/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.k8s.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * AtSpec defines the desired state of At
 */
@ApiModel(description = "AtSpec defines the desired state of At")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-06-13T03:43:40.301Z[Etc/UTC]")
public class V1alpha1AtSpec {
  public static final String SERIALIZED_NAME_COMMAND = "command";
  @SerializedName(SERIALIZED_NAME_COMMAND)
  private String command;

  public static final String SERIALIZED_NAME_SCHEDULE = "schedule";
  @SerializedName(SERIALIZED_NAME_SCHEDULE)
  private String schedule;


  public V1alpha1AtSpec command(String command) {
    
    this.command = command;
    return this;
  }

   /**
   * Command is the desired command (executed in a Bash shell) to be executed.
   * @return command
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Command is the desired command (executed in a Bash shell) to be executed.")

  public String getCommand() {
    return command;
  }


  public void setCommand(String command) {
    this.command = command;
  }


  public V1alpha1AtSpec schedule(String schedule) {
    
    this.schedule = schedule;
    return this;
  }

   /**
   * Schedule is the desired time the command is supposed to be executed. Note: the format used here is UTC time https://www.utctime.net
   * @return schedule
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Schedule is the desired time the command is supposed to be executed. Note: the format used here is UTC time https://www.utctime.net")

  public String getSchedule() {
    return schedule;
  }


  public void setSchedule(String schedule) {
    this.schedule = schedule;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1AtSpec v1alpha1AtSpec = (V1alpha1AtSpec) o;
    return Objects.equals(this.command, v1alpha1AtSpec.command) &&
        Objects.equals(this.schedule, v1alpha1AtSpec.schedule);
  }

  @Override
  public int hashCode() {
    return Objects.hash(command, schedule);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1AtSpec {\n");
    sb.append("    command: ").append(toIndentedString(command)).append("\n");
    sb.append("    schedule: ").append(toIndentedString(schedule)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

